const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={groups:[],skills:[],activeId:'',timeMode:'manual',modeGroupId:'',messages:[],cursor:'',hasMore:false,totalHint:0,selectionMode:'all',excluded:new Set(),included:new Set(),loading:false,extractTask:{status:'idle',running:false}};

async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json','X-CoreInsight-Protocol':'1'},...options});let body=null;try{body=await response.json()}catch{}if(!response.ok){const message=body?.msg||body?.detail||`请求失败 (${response.status})`;throw new Error(message)}return body&&typeof body==='object'&&'code' in body&&'data' in body?body.data:body}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add('hidden'),2800)}
function active(){return state.groups.find(group=>group.groupId===state.activeId)}
function localValue(date){const offset=date.getTimezoneOffset()*60000;return new Date(date-offset).toISOString().slice(0,16)}
function localSeconds(date){const offset=date.getTimezoneOffset()*60000;return new Date(date-offset).toISOString().slice(0,19)}
function rangeValues(range){const now=new Date();if(range==='all')return['',''];if(range==='custom')return[$('#start-time').value,$('#end-time').value];const end=localValue(now);let start=new Date(now);if(range==='today')start.setHours(0,0,0,0);else start.setDate(start.getDate()-Number(range[0]));return[localValue(start),end]}
function messageType(value){return({TEXT_MSG:'文本',PICTURE_MSG:'图片',FILE_MSG:'文件',CARD_MSG:'卡片',NOTICE_MSG:'通知'})[value]||value||'未知'}

function renderGroups(){const list=$('#group-list');list.innerHTML='';$('#group-count').textContent=`${state.groups.length} 个群组`;$('#group-empty').classList.toggle('hidden',state.groups.length>0);for(const group of state.groups){const item=document.createElement('div');item.className=`group-item${group.groupId===state.activeId?' active':''}`;item.innerHTML=`<i class="dot ${group.status}"></i><div><b></b><small></small></div>`;item.querySelector('b').textContent=group.name||group.groupId;item.querySelector('small').textContent=group.groupId;item.onclick=()=>selectGroup(group.groupId);list.appendChild(item)}}
function selectGroup(groupId){state.activeId=groupId;state.modeGroupId='';state.messages=[];resetSelection();renderGroups();fillConfig()}
function fillConfig(){const group=active();$('#blank-state').classList.toggle('hidden',!!group);$('#config-form').classList.toggle('hidden',!group);if(!group)return;if(state.modeGroupId!==group.groupId){state.timeMode=group.scheduleEnabled?'scheduled':'manual';state.modeGroupId=group.groupId}$('#config-title').textContent=group.name||group.groupId;$('#group-id').value=group.groupId;$('#group-name').value=group.name||'';$('#start-time').value=(group.startTime||'').slice(0,16).replace(' ','T');$('#end-time').value=(group.endTime||'').slice(0,16).replace(' ','T');const cursor=group.scheduleCursor||group.scheduleLastRun||group.scheduleSince||'';$('#schedule-since').value=(cursor||localSeconds(new Date())).slice(0,19).replace(' ','T');$('#skill-id').value=group.skillId||state.skills[0]?.id||'';renderSkillDescription();$(`input[name="mode"][value="${group.extractMode}"]`).checked=true;const range=group.quickRange||'7d';setRange(range,range!=='all'&&range!=='custom'&&!group.startTime&&!group.endTime);const labels={idle:'空闲',extracting:'提取中',scheduled:'已定时'};$('#status-pill').textContent=labels[group.status]||'空闲';$('#schedule-button').textContent=group.scheduleEnabled?'修改定时':'设置定时';$('#preview-summary').textContent='查看群组消息，取消勾选不需要提取的内容';$('#schedule-cursor-note').textContent=group.scheduleEnabled?`当前成功游标：${cursor||'-'}；失败或取消不会推进。`:'首次从 since 提取，成功后由系统自动推进游标。';setTimeMode(state.timeMode)}
function setTimeMode(mode){state.timeMode=mode;$$('[data-time-mode]').forEach(button=>button.classList.toggle('active',button.dataset.timeMode===mode));const scheduled=mode==='scheduled';$('#manual-range-panel').classList.toggle('hidden',scheduled);$('#scheduled-range-panel').classList.toggle('hidden',!scheduled);$('#preview-section').classList.toggle('hidden',scheduled);$('#extract-button').classList.toggle('hidden',scheduled);$('#schedule-button').classList.toggle('hidden',!scheduled);const group=active();$('#cancel-schedule').classList.toggle('hidden',!scheduled||!group?.scheduleEnabled);if(scheduled&&!$('#schedule-since').value)$('#schedule-since').value=localSeconds(new Date())}
function setRange(range,update=true){$$('[data-range]').forEach(button=>button.classList.toggle('active',button.dataset.range===range));if(update){const [start,end]=rangeValues(range);$('#start-time').value=start;$('#end-time').value=end}const group=active();if(group)group.quickRange=range}
function formPayload(){const group=active();return{...group,name:$('#group-name').value.trim(),startTime:$('#start-time').value,endTime:$('#end-time').value,quickRange:$('.range-buttons .active')?.dataset.range||'custom',skillId:$('#skill-id').value,extractMode:$('input[name="mode"]:checked').value}}

function renderSkillDescription(){const skill=state.skills.find(item=>item.id===$('#skill-id').value);$('#skill-description').textContent=skill?.description||''}
async function loadSkills(){try{state.skills=await api('/welink/skill/list');$('#skill-id').innerHTML='';for(const skill of state.skills){const option=document.createElement('option');option.value=skill.id;option.textContent=skill.name;$('#skill-id').appendChild(option)}fillConfig()}catch(error){toast(error.message,true)}}

async function loadGroups(){try{state.groups=await api('/welink/group/list');if(state.activeId&&!state.groups.some(g=>g.groupId===state.activeId))state.activeId='';if(!state.activeId&&state.groups.length)state.activeId=state.groups[0].groupId;renderGroups();fillConfig()}catch(error){toast(error.message,true)}}
async function addGroup(event){event.preventDefault();const groupId=$('#new-group-id').value.trim();if(!groupId)return toast('请输入群组 ID',true);try{const group=await api('/welink/group/add',{method:'POST',body:JSON.stringify({groupId,name:$('#new-group-name').value.trim()})});state.groups.push(group);state.activeId=group.groupId;$('#add-form').reset();$('#add-form').classList.add('hidden');renderGroups();fillConfig();toast('群组已添加')}catch(error){toast(error.message,true)}}
async function saveConfig(event){event.preventDefault();try{const group=await api('/welink/group/update',{method:'PUT',body:JSON.stringify(formPayload())});state.groups=state.groups.map(item=>item.groupId===group.groupId?group:item);renderGroups();fillConfig();toast('配置已保存')}catch(error){toast(error.message,true)}}
async function deleteGroup(){const group=active();if(!group||!confirm(`确定删除“${group.name||group.groupId}”吗？\n这不会删除 WeLink 中的原始消息。`))return;try{await api('/welink/group/delete',{method:'DELETE',body:JSON.stringify({groupId:group.groupId})});state.groups=state.groups.filter(item=>item.groupId!==group.groupId);state.activeId=state.groups[0]?.groupId||'';renderGroups();fillConfig();toast('群组已删除')}catch(error){toast(error.message,true)}}

function renderExtractTask(){const task=state.extractTask||{},button=$('#extract-button'),progress=$('#extract-progress');button.classList.toggle('cancel',!!task.running);button.disabled=false;button.innerHTML=task.running?'取消提取 <span>×</span>':'提取 <span>→</span>';const counts=task.scanned?` · 扫描 ${task.scanned} / 选中 ${task.selected}`:'';progress.textContent=(task.message||'')+counts;const labels={fetching:'读取中',workspace:'准备资料',skill:'Skill 执行中',pushing:'结果写入中',done:'已完成',failed:'失败',cancelled:'已取消',idle:'空闲'};$('#status-pill').textContent=labels[task.status]||task.status||'空闲';if(task.error)progress.textContent=task.error}
async function waitExtractStopped(){for(let i=0;i<40;i++){state.extractTask=await api('/welink/extract/status');if(!state.extractTask.running)return;await new Promise(resolve=>setTimeout(resolve,250))}throw new Error('当前提取尚未停止，请稍后重试')}
async function startOrCancelExtract(){const group=active();if(!group)return;if(state.extractTask?.running){if(!confirm('正在提取中，是否中断并按当前配置重新提取？'))return;try{await api('/welink/extract/cancel',{method:'POST',body:'{}'});await waitExtractStopped()}catch(error){return toast(error.message,true)}}const config=formPayload();try{if(group.scheduleEnabled){if(!confirm('已设定定时提取，手动提取将取消定时任务，是否继续？'))return;await api('/welink/schedule/cancel',{method:'POST',body:JSON.stringify({groupId:group.groupId})});group.scheduleEnabled=false;group.status='idle';fillConfig()}const endTime=config.endTime||localValue(new Date());const payload={groupId:group.groupId,uploadBy:'w00899061',startTime:config.startTime||null,endTime,skillId:config.skillId,extractMode:config.extractMode,selection:selectionPayload()};state.extractTask=await api('/welink/extract',{method:'POST',body:JSON.stringify(payload)});renderExtractTask();toast(config.extractMode==='draft'?'草稿 Skill 提取任务已启动':'Skill 提取任务已启动')}catch(error){toast(error.message,true)}}
async function pollExtract(){try{const previous=state.extractTask?.status;state.extractTask=await api('/welink/extract/status');if(state.extractTask.running&&state.extractTask.groupId){const group=state.groups.find(item=>item.groupId===state.extractTask.groupId);if(group)group.status='extracting';renderGroups()}renderExtractTask();if(previous&&previous!==state.extractTask.status&&!state.extractTask.running)await loadGroups();if(previous&&previous!==state.extractTask.status&&state.extractTask.status==='done')toast(state.extractTask.message||'经验提取并入库完成');if(previous&&previous!==state.extractTask.status&&state.extractTask.status==='failed')toast(state.extractTask.error||'提取失败',true)}catch{}}

function toggleScheduleFields(){const custom=$('#schedule-freq').value==='custom';$('#schedule-time-wrap').classList.toggle('hidden',custom);$('#schedule-cron-wrap').classList.toggle('hidden',!custom)}
function closeSchedule(){$('#schedule-modal').classList.add('hidden')}
async function openSchedule(){const group=active();if(!group)return;if(state.extractTask?.running&&state.extractTask.groupId===group.groupId){if(!confirm('正在提取中，设定定时任务将中断当前提取，是否继续？'))return;try{await api('/welink/extract/cancel',{method:'POST',body:JSON.stringify({groupId:group.groupId})});await waitExtractStopped()}catch(error){return toast(error.message,true)}}$('#schedule-freq').value=group.scheduleFreq||'daily';$('#schedule-time').value=group.scheduleTime||'09:00:00';$('#schedule-cron').value=group.scheduleCron||'';const cursor=group.scheduleCursor||group.scheduleLastRun||'';$('#schedule-note').textContent=group.scheduleNextRun?`当前游标：${cursor||'-'} · 下次执行：${group.scheduleNextRun.replace('T',' ')}`:'首次保存后，从页面填写的 since 开始增量提取。';toggleScheduleFields();$('#schedule-modal').classList.remove('hidden')}
async function saveSchedule(event){event.preventDefault();const group=active();if(!group)return;const config=formPayload(),since=$('#schedule-since').value;if(!since)return toast('请填写定时增量起点 since',true);const cursor=(group.scheduleCursor||group.scheduleLastRun||'').slice(0,19).replace(' ','T'),sinceChanged=!!group.scheduleEnabled&&since!==cursor;if(sinceChanged&&!confirm('修改 since 会重置增量游标，可能重复提取历史消息，是否继续？'))return;const payload={groupId:group.groupId,uploadBy:'w00899061',skillId:config.skillId,extractMode:config.extractMode,scheduleFreq:$('#schedule-freq').value,scheduleTime:$('#schedule-time').value||'09:00:00',scheduleCron:$('#schedule-cron').value.trim()};if(!group.scheduleEnabled||sinceChanged)payload.since=since;try{const saved=await api('/welink/schedule/set',{method:'POST',body:JSON.stringify(payload)});state.groups=state.groups.map(item=>item.groupId===saved.groupId?saved:item);state.timeMode='scheduled';fillConfig();renderGroups();closeSchedule();toast('定时增量任务已保存')}catch(error){toast(error.message,true)}}
async function cancelSchedule(){const group=active();if(!group||!confirm('确定取消该群组的定时提取吗？'))return;try{const saved=await api('/welink/schedule/cancel',{method:'POST',body:JSON.stringify({groupId:group.groupId})});state.groups=state.groups.map(item=>item.groupId===saved.groupId?saved:item);fillConfig();renderGroups();toast('定时任务已取消')}catch(error){toast(error.message,true)}}

function resetSelection(){state.selectionMode='all';state.excluded=new Set();state.included=new Set()}
function isSelected(id){return state.selectionMode==='all'?!state.excluded.has(id):state.included.has(id)}
function setMessageSelected(id,checked){const target=state.selectionMode==='all'?state.excluded:state.included;if(state.selectionMode==='all'){checked?target.delete(id):target.add(id)}else{checked?target.add(id):target.delete(id)}}
function selectionPayload(){return state.selectionMode==='all'?{mode:'all',excludedMessageIds:[...state.excluded]}:{mode:'explicit',selectedMessageIds:[...state.included]}}
function openPreview(){const group=active();if(!group)return;$('#preview-modal').classList.remove('hidden');$('#modal-title').textContent=`${group.name||group.groupId} · 消息预览`;loadMessages(true)}
function closePreview(){$('#preview-modal').classList.add('hidden')}
async function loadMessages(reset=false){const group=active();if(!group||state.loading)return;if(reset){state.messages=[];state.cursor='';state.hasMore=false;state.totalHint=0;resetSelection()}state.loading=true;renderCount();$('#message-loading').classList.remove('hidden');if(reset){$('#message-empty').classList.add('hidden');$('#message-table').classList.add('hidden')}const startTime=$('#start-time').value||null,endTime=$('#end-time').value||null;$('#modal-range').textContent=startTime||endTime?`${startTime?.replace('T',' ')||'最早'} 至 ${endTime?.replace('T',' ')||'现在'}`:'WeLink 当前账号可读取的全部历史';try{const page=await api('/welink/message/page',{method:'POST',body:JSON.stringify({groupId:group.groupId,startTime,endTime,cursor:state.cursor,limit:100})});const known=new Set(state.messages.map(item=>item.id));state.messages.push(...page.items.filter(item=>!known.has(item.id)));state.cursor=page.nextCursor||'';state.hasMore=!!page.hasMore;state.totalHint=Math.max(state.totalHint,page.totalHint||0)}catch(error){if(reset)state.messages=[];toast(error.message,true)}finally{state.loading=false;$('#message-loading').classList.add('hidden');renderMessages()}}
function renderMessages(){const body=$('#message-body');body.innerHTML='';$('#message-empty').classList.toggle('hidden',state.messages.length>0);$('#message-table').classList.toggle('hidden',!state.messages.length);for(const message of state.messages){const row=document.createElement('tr');row.innerHTML='<td><input type="checkbox"></td><td></td><td></td><td></td><td class="message-content"></td>';const check=row.querySelector('input');check.checked=isSelected(message.id);check.onchange=()=>{setMessageSelected(message.id,check.checked);renderCount()};const cells=row.querySelectorAll('td');cells[1].textContent=(message.time||'').replace('T',' ');cells[2].textContent=message.sender||'-';cells[3].textContent=messageType(message.contentType);cells[4].textContent=message.content||'';body.appendChild(row)}renderCount()}
function renderCount(){const selectedLoaded=state.messages.filter(item=>isSelected(item.id)).length;$('#selected-count').textContent=state.selectionMode==='all'?`范围内全选 · 排除 ${state.excluded.size} 条`:`已明确选择 ${state.included.size} 条`;$('#message-total').textContent=`已加载 ${state.messages.length} 条${state.hasMore?' · 仍有更早消息':' · 已到底'}`;$('#check-all').checked=state.selectionMode==='all'&&state.excluded.size===0;$('#check-all').indeterminate=(state.selectionMode==='all'&&state.excluded.size>0)||(state.selectionMode==='explicit'&&selectedLoaded>0);$('#load-more').classList.toggle('hidden',!state.hasMore);$('#load-more').disabled=state.loading}

function bind(){$('#show-add').onclick=()=>{$('#add-form').classList.toggle('hidden');if(!$('#add-form').classList.contains('hidden'))$('#new-group-id').focus()};$('#cancel-add').onclick=()=>$('#add-form').classList.add('hidden');$('#add-form').onsubmit=addGroup;$('#config-form').onsubmit=saveConfig;$('#delete-group').onclick=deleteGroup;$$('[data-time-mode]').forEach(button=>button.onclick=()=>setTimeMode(button.dataset.timeMode));$$('[data-range]').forEach(button=>button.onclick=()=>setRange(button.dataset.range));$$('[data-since]').forEach(button=>button.onclick=()=>{const now=new Date(),kind=button.dataset.since;if(kind==='today')now.setHours(0,0,0,0);else if(kind==='7d')now.setDate(now.getDate()-7);$('#schedule-since').value=localSeconds(now)});$('#start-time').onchange=$('#end-time').onchange=()=>setRange('custom',false);$('#skill-id').onchange=renderSkillDescription;$('#preview-button').onclick=openPreview;$('#close-preview').onclick=closePreview;$('#preview-modal').onclick=event=>{if(event.target===$('#preview-modal'))closePreview()};$('#refresh-preview').onclick=()=>loadMessages(true);$('#load-more').onclick=()=>loadMessages(false);$('#check-all').onchange=event=>{if(event.target.checked){state.selectionMode='all';state.excluded.clear();state.included.clear()}else{state.selectionMode='explicit';state.included.clear();state.excluded.clear()}renderMessages()};$('#confirm-preview').onclick=()=>{const selection=selectionPayload();$('#preview-summary').textContent=selection.mode==='all'?`范围内全部消息（排除 ${selection.excludedMessageIds.length} 条）`:`已选择 ${selection.selectedMessageIds.length} 条消息`;closePreview();toast('消息选择条件已保留')};$('#extract-button').onclick=startOrCancelExtract;$('#schedule-button').onclick=openSchedule;$('#cancel-schedule').onclick=cancelSchedule;$('#schedule-form').onsubmit=saveSchedule;$('#schedule-freq').onchange=toggleScheduleFields;$('#close-schedule').onclick=$('#schedule-back').onclick=closeSchedule;$('#schedule-modal').onclick=event=>{if(event.target===$('#schedule-modal'))closeSchedule()}}

bind();loadSkills();loadGroups();pollExtract();setInterval(pollExtract,2000);

// Outlook mail demo
const emailState={config:null,folders:[],items:[],selected:new Set(),page:0,pageSize:50,total:0,totalExact:false,hasMore:false,ruleKind:'rules',task:{running:false,status:'idle'}};
function hasActiveEmailRule(){return !!emailState.config?.rules?.some(rule=>rule.enabled&&(rule.subjectKeywords?.length||rule.bodyKeywords?.length||rule.senders?.length))}
function renderEmailRuleWarning(){const active=hasActiveEmailRule();$('#email-rule-warning').classList.toggle('hidden',active);$('#email-rules-button').classList.toggle('active',active);$('#email-matched-only').disabled=!active;if(!active)$('#email-matched-only').checked=false}
function openEmailRules(){emailState.ruleKind='rules';$$('[data-email-rule-kind]').forEach((item,index)=>item.classList.toggle('active',index===0));renderRuleRows();$('#email-rules-popover').classList.remove('hidden')}
function closeEmailRules(){$('#email-rules-popover').classList.add('hidden')}
function emailFolders(){return $$('.email-folder input:checked').map(input=>input.value)}
function emailRange(kind){const now=new Date();if(kind==='all')return['',''];if(kind==='custom')return[$('#email-start').value,$('#email-end').value];const start=new Date(now);if(kind==='today')start.setHours(0,0,0,0);else start.setDate(start.getDate()-Number(kind.replace('d','')));return[localValue(start),localValue(now)]}
function setEmailRange(kind,update=true){$$('[data-email-range]').forEach(button=>button.classList.toggle('active',button.dataset.emailRange===kind));if(update){const [start,end]=emailRange(kind);$('#email-start').value=start;$('#email-end').value=end}}
function openEmailModal(id){$(`#${id}`).classList.remove('hidden')}
function closeEmailModal(id){$(`#${id}`).classList.add('hidden')}
function syncEmailActionFields(){const config=emailState.config||{};for(const kind of ['manual','schedule']){const prefix=kind==='schedule'?'email-schedule':'email';$(`#${prefix}-upload-by`).value=config.uploadBy||'w00899061';$(`#${prefix}-mode`).value=config.extractMode||'direct';if(config.skillId)$(`#${prefix}-skill`).value=config.skillId}}
function emailActionValues(kind){const prefix=kind==='schedule'?'email-schedule':'email';return{skillId:$(`#${prefix}-skill`).value,extractMode:$(`#${prefix}-mode`).value,uploadBy:$(`#${prefix}-upload-by`).value.trim()}}
async function loadEmailSkills(){try{const skills=await api('/email/skill/list'),options=skills.map(skill=>`<option value="${skill.id}">${skill.name}</option>`).join('');$('#email-skill').innerHTML=options;$('#email-schedule-skill').innerHTML=options;syncEmailActionFields()}catch(error){toast(error.message,true)}}
async function loadEmailConfig(){try{emailState.config=await api('/email/config');syncEmailActionFields();renderEmailFolders();renderEmailScheduleState();renderEmailRuleWarning()}catch(error){toast(error.message,true)}}
async function loadEmailFolders(){const button=$('#refresh-email-folders'),target=$('#email-folder-list');button.disabled=true;target.innerHTML='<div class="sidebar-loading"><i></i><span>正在读取文件夹…</span></div>';try{emailState.folders=await api('/email/folder/list');renderEmailFolders()}catch(error){target.innerHTML='<div class="sidebar-empty compact">文件夹读取失败，可点击刷新重试</div>';toast(error.message,true)}finally{button.disabled=false}}
function renderEmailFolders(){const target=$('#email-folder-list');if(!emailState.folders.length){$('#email-folder-count').textContent='默认收件箱';target.innerHTML='<div class="sidebar-empty compact">点击刷新读取 Outlook 文件夹</div>';return}const configured=emailState.config?.folders||[];const selected=new Set(configured);if(!configured.length){const inbox=emailState.folders.find(folder=>folder.isDefault)||emailState.folders.find(folder=>/^(inbox|收件箱)$/i.test(folder.name));if(inbox)selected.add(inbox.path)}$('#email-folder-count').textContent=selected.size?`已选 ${selected.size} 个`:'默认收件箱';target.innerHTML='';for(const folder of emailState.folders){const label=document.createElement('label');label.className='email-folder';label.style.paddingLeft=`${8+Math.min(folder.depth,4)*12}px`;const check=document.createElement('input');check.type='checkbox';check.value=folder.path;check.checked=selected.has(folder.path);check.onchange=()=>{$('#email-folder-count').textContent=emailFolders().length?`已选 ${emailFolders().length} 个`:'默认收件箱'};const span=document.createElement('span');span.textContent=folder.name;span.title=folder.path;label.append(check,span);target.appendChild(label)}}
async function saveEmailConfig(actionKind=null){const current=emailState.config||{},action=actionKind?emailActionValues(actionKind):{skillId:current.skillId||'email-experience-extractor',extractMode:current.extractMode||'direct',uploadBy:current.uploadBy||'w00899061'},payload={...current,folders:emailFolders(),rules:current.rules||[],blacklist:current.blacklist||[],...action};emailState.config=await api('/email/config',{method:'PUT',body:JSON.stringify(payload)});syncEmailActionFields();renderEmailRuleWarning();renderEmailScheduleState();return emailState.config}
async function loadEmailMessages(reset=true,persist=true){if(reset)emailState.page=0;$('#email-loading').classList.remove('hidden');$('#email-empty').classList.add('hidden');try{if(persist)await saveEmailConfig();const folders=persist?emailFolders():(emailState.config?.folders||[]),payload={folders,startTime:$('#email-start').value||null,endTime:$('#email-end').value||null,query:$('#email-query').value.trim(),matchedOnly:$('#email-matched-only').checked,offset:emailState.page*emailState.pageSize,limit:emailState.pageSize};const result=await api('/email/message/list',{method:'POST',body:JSON.stringify(payload)});emailState.items=result.items||[];emailState.total=result.total||0;emailState.totalExact=!!result.totalExact;emailState.hasMore=!!result.hasMore;renderEmailMessages()}catch(error){emailState.items=[];emailState.total=0;emailState.totalExact=false;renderEmailMessages();toast(error.message,true)}finally{$('#email-loading').classList.add('hidden')}}
function renderEmailMessages(){const body=$('#email-body');body.innerHTML='';for(const item of emailState.items){const row=document.createElement('tr');row.innerHTML='<td><input type="checkbox"></td><td></td><td></td><td class="subject"></td><td></td><td></td><td><button class="preview-link">预览</button></td>';const cells=row.querySelectorAll('td'),check=row.querySelector('input');check.checked=emailState.selected.has(item.id);check.onchange=()=>{check.checked?emailState.selected.add(item.id):emailState.selected.delete(item.id);renderEmailTask()};cells[1].textContent=(item.receivedTime||'').replace('T',' ');cells[2].textContent=item.senderName||item.senderEmail||'-';cells[2].title=`${item.senderName||''} ${item.senderEmail||''}`;cells[3].textContent=item.subject||'(无主题)';cells[3].title=item.subject||'';cells[4].textContent=item.conversationTopic||'-';const badge=document.createElement('span');badge.className=`rule-badge${item.blockedRule?' blocked':''}`;badge.textContent=item.blockedRule?`排除 · ${item.blockedRule}`:(item.matchedRule||'—');cells[5].appendChild(badge);row.querySelector('.preview-link').onclick=()=>previewEmail(item);body.appendChild(row)}$('#email-empty').classList.toggle('hidden',emailState.items.length>0);const loaded=emailState.page*emailState.pageSize+emailState.items.length,pages=Math.max(1,Math.ceil(emailState.total/emailState.pageSize));$('#email-total').textContent=`${emailState.totalExact?`共 ${emailState.total} 封`:`已加载 ${loaded}${emailState.hasMore?' +':''} 封`} · 已选 ${emailState.selected.size} 封`;$('#email-page').textContent=emailState.totalExact?`${emailState.page+1} / ${pages}`:`第 ${emailState.page+1} 页`;$('#email-prev').disabled=emailState.page===0;$('#email-next').disabled=!emailState.hasMore;$('#email-check-all').checked=emailState.items.length>0&&emailState.items.every(item=>emailState.selected.has(item.id));renderEmailTask()}
async function previewEmail(item){openEmailModal('email-detail-modal');$('#email-detail-title').textContent=item.subject||'无主题邮件';$('#email-detail-meta').textContent='正在读取正文…';$('#email-detail-body').textContent='';try{const detail=await api('/email/message/get',{method:'POST',body:JSON.stringify({itemId:item.id})});$('#email-detail-meta').textContent=`${detail.senderName||''} <${detail.senderEmail||''}> · ${detail.receivedTime||''}`;const frame=document.createElement('iframe');frame.setAttribute('sandbox','');frame.style.cssText='width:100%;height:100%;border:0';frame.srcdoc=detail.htmlBody||`<pre>${escapeHtml(detail.body||'')}</pre>`;$('#email-detail-body').appendChild(frame)}catch(error){$('#email-detail-body').textContent=error.message}}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}

function readRuleRows(){return $$('.email-rule-row').map(row=>({id:row.dataset.id||'',name:row.querySelector('[data-field=name]').value.trim(),subjectKeywords:splitKeywords(row.querySelector('[data-field=subject]').value),bodyKeywords:splitKeywords(row.querySelector('[data-field=body]').value),senders:splitKeywords(row.querySelector('[data-field=senders]').value),logic:row.querySelector('[data-field=logic]').value,enabled:row.querySelector('[data-field=enabled]').checked})).filter(rule=>rule.name)}
function splitKeywords(value){return value.split(/[,，\n]/).map(item=>item.trim()).filter(Boolean)}
function captureRuleRows(){if(emailState.config)emailState.config[emailState.ruleKind]=readRuleRows()}
function renderRuleRows(){const target=$('#email-rule-list');target.innerHTML='';const rules=emailState.config?.[emailState.ruleKind]||[];for(const rule of rules)addRuleRow(rule);if(!rules.length)target.innerHTML='<div class="sidebar-empty compact">还没有规则，点击下方添加</div>'}
function addRuleRow(rule={}){const target=$('#email-rule-list');if(target.querySelector('.sidebar-empty'))target.innerHTML='';const row=document.createElement('div');row.className='email-rule-row';row.dataset.id=rule.id||'';row.innerHTML='<input type="checkbox" data-field="enabled"><input data-field="name" placeholder="规则名称"><input data-field="subject" placeholder="主题关键词，逗号分隔"><input data-field="body" placeholder="正文关键词，逗号分隔"><input data-field="senders" placeholder="发件人姓名/邮箱"><select data-field="logic"><option>OR</option><option>AND</option></select><button title="删除">×</button>';row.querySelector('[data-field=enabled]').checked=rule.enabled!==false;row.querySelector('[data-field=name]').value=rule.name||'';row.querySelector('[data-field=subject]').value=(rule.subjectKeywords||[]).join(', ');row.querySelector('[data-field=body]').value=(rule.bodyKeywords||[]).join(', ');row.querySelector('[data-field=senders]').value=(rule.senders||[]).join(', ');row.querySelector('[data-field=logic]').value=rule.logic||'OR';row.querySelector('button').onclick=()=>row.remove();target.appendChild(row)}
async function saveEmailRules(){captureRuleRows();try{await saveEmailConfig();closeEmailRules();toast('邮件规则已保存');await loadEmailMessages()}catch(error){toast(error.message,true)}}

async function toggleEmailStartMenu(){if(emailState.task.running){try{await api('/email/extract/cancel',{method:'POST',body:'{}'});toast('正在取消邮件提取')}catch(error){toast(error.message,true)}return}renderEmailTask();$('#email-start-menu').classList.toggle('hidden')}
function openOrCancelEmailExtract(){$('#email-start-menu').classList.add('hidden');if(!emailState.selected.size)return toast('请先勾选需要提取的邮件',true);syncEmailActionFields();$('#email-extract-summary').textContent=`已选择 ${emailState.selected.size} 封邮件，请确认提取配置。`;openEmailModal('email-extract-modal')}
async function submitEmailExtract(event){event.preventDefault();try{await saveEmailConfig('manual');const action=emailActionValues('manual'),payload={folders:emailFolders(),startTime:$('#email-start').value||null,endTime:$('#email-end').value||null,query:$('#email-query').value.trim(),matchedOnly:$('#email-matched-only').checked,...action,selection:{mode:'explicit',selectedItemIds:[...emailState.selected]}};emailState.task=await api('/email/extract',{method:'POST',body:JSON.stringify(payload)});closeEmailModal('email-extract-modal');renderEmailTask();toast('邮件 Skill 提取任务已启动')}catch(error){toast(error.message,true)}}
function renderEmailTask(){const task=emailState.task||{},start=$('#email-start-button'),selected=$('#email-extract-button');$('#email-start-selected-count').textContent=`当前选中 ${emailState.selected.size} 封邮件`;selected.disabled=!emailState.selected.size||!!task.running;start.classList.toggle('cancel',!!task.running);start.innerHTML=task.running?`停止提取 ${task.processed||0}/${task.selected||0}`:'<span>▶</span> 启动 <i></i>';const titles={idle:'准备就绪',fetching:'读取邮件',workspace:'转换邮件与附件',skill:'Skill 执行中',pushing:'写入经验',done:'提取完成',failed:'提取失败',cancelled:'已取消'};$('#email-task-title').textContent=titles[task.status]||task.status||'准备就绪';const count=task.selected?` · ${task.processed||0}/${task.selected}`:'';$('#email-task-message').textContent=(task.error||task.message||'选择邮件后即可提取')+count}
async function pollEmailTask(){try{const previous=emailState.task.status;emailState.task=await api('/email/extract/status');renderEmailTask();if(previous&&previous!==emailState.task.status&&!emailState.task.running&&emailState.task.status==='done'){emailState.selected.clear();renderEmailMessages();toast(emailState.task.message||'邮件提取完成')}if(previous&&previous!==emailState.task.status&&emailState.task.status==='failed')toast(emailState.task.error||'邮件提取失败',true)}catch{}}
function renderEmailScheduleState(){const config=emailState.config||{},button=$('#email-schedule-button');$('#email-cancel-schedule').classList.toggle('hidden',!config.scheduleEnabled);button.querySelector('b').textContent=config.scheduleEnabled?'修改定时':'启动定时';button.querySelector('span').textContent=config.scheduleEnabled?`下次执行：${config.scheduleNextRun||'-'}`:'使用已保存的提取规则与黑名单'}
function toggleEmailScheduleFields(){const custom=$('#email-schedule-freq').value==='custom';$('#email-schedule-time-wrap').classList.toggle('hidden',custom);$('#email-schedule-cron-wrap').classList.toggle('hidden',!custom)}
function openEmailSchedule(){$('#email-start-menu').classList.add('hidden');if(!hasActiveEmailRule()){renderEmailRuleWarning();toast('定时增量提取必须先配置并启用至少一条有效的提取规则',true);return}const config=emailState.config||{};syncEmailActionFields();$('#email-since').value=(config.scheduleCursor||config.scheduleSince||localSeconds(new Date())).replace(' ','T').slice(0,19);$('#email-schedule-freq').value=config.scheduleFreq||'daily';$('#email-schedule-time').value=config.scheduleTime||'09:00:00';$('#email-schedule-cron').value=config.scheduleCron||'';$('#email-schedule-note').textContent=config.scheduleEnabled?`当前游标：${config.scheduleCursor||'-'} · 下次执行：${config.scheduleNextRun||'-'}`:'定时任务仅处理提取规则命中且未被黑名单排除的增量邮件。';toggleEmailScheduleFields();openEmailModal('email-schedule-modal')}
async function saveEmailSchedule(event){event.preventDefault();try{await saveEmailConfig('schedule');const config=emailState.config||{},action=emailActionValues('schedule'),since=$('#email-since').value,cursor=(config.scheduleCursor||'').replace(' ','T').slice(0,19);const payload={folders:emailFolders(),...action,scheduleFreq:$('#email-schedule-freq').value,scheduleTime:$('#email-schedule-time').value||'09:00:00',scheduleCron:$('#email-schedule-cron').value.trim()};if(!config.scheduleEnabled||since!==cursor)payload.since=since;emailState.config=await api('/email/schedule/set',{method:'POST',body:JSON.stringify(payload)});syncEmailActionFields();renderEmailScheduleState();closeEmailModal('email-schedule-modal');toast('邮件定时增量任务已保存')}catch(error){toast(error.message,true)}}
async function cancelEmailSchedule(){if(!confirm('确定取消邮件定时提取吗？增量游标会保留。'))return;try{emailState.config=await api('/email/schedule/cancel',{method:'POST',body:'{}'});renderEmailScheduleState();closeEmailModal('email-schedule-modal');toast('邮件定时任务已取消')}catch(error){toast(error.message,true)}}
function bindEmail(){$$('[data-product]').forEach(button=>button.onclick=()=>{$$('[data-product]').forEach(item=>item.classList.toggle('active',item===button));$('#email-demo').classList.toggle('hidden',button.dataset.product!=='email');$('#welink-demo').classList.toggle('hidden',button.dataset.product!=='welink')});$$('[data-email-range]').forEach(button=>button.onclick=()=>setEmailRange(button.dataset.emailRange));$('#email-start').onchange=$('#email-end').onchange=()=>setEmailRange('custom',false);$('#refresh-email-folders').onclick=loadEmailFolders;$('#refresh-email-list').onclick=()=>loadEmailMessages(true);$('#email-query').onkeydown=event=>{if(event.key==='Enter')loadEmailMessages(true)};$('#email-matched-only').onchange=()=>loadEmailMessages(true);$('#email-prev').onclick=()=>{if(emailState.page){emailState.page--;loadEmailMessages(false)}};$('#email-next').onclick=()=>{if(emailState.hasMore){emailState.page++;loadEmailMessages(false)}};$('#email-check-all').onchange=event=>{for(const item of emailState.items)event.target.checked?emailState.selected.add(item.id):emailState.selected.delete(item.id);renderEmailMessages()};$('#email-start-button').onclick=toggleEmailStartMenu;$('#email-extract-button').onclick=openOrCancelEmailExtract;$('#email-extract-form').onsubmit=submitEmailExtract;$('#email-rules-button').onclick=openEmailRules;$('#email-close-rules').onclick=closeEmailRules;$('#email-configure-rules').onclick=openEmailRules;$$('[data-email-rule-kind]').forEach(button=>button.onclick=()=>{captureRuleRows();emailState.ruleKind=button.dataset.emailRuleKind;$$('[data-email-rule-kind]').forEach(item=>item.classList.toggle('active',item===button));renderRuleRows()});$('#email-add-rule').onclick=()=>addRuleRow();$('#email-save-rules').onclick=saveEmailRules;$$('[data-email-close]').forEach(button=>button.onclick=()=>closeEmailModal(button.dataset.emailClose));$('#email-schedule-button').onclick=openEmailSchedule;$('#email-cancel-schedule').onclick=cancelEmailSchedule;$('#email-schedule-form').onsubmit=saveEmailSchedule;$('#email-schedule-freq').onchange=toggleEmailScheduleFields}
async function initializeEmail(){bindEmail();setEmailRange('7d');await Promise.all([loadEmailSkills(),loadEmailConfig()]);await loadEmailMessages(true,false);loadEmailFolders();pollEmailTask();setInterval(pollEmailTask,2000)}
initializeEmail();
