$ErrorActionPreference = "Stop"

$ProjectDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$BuildVenv = Join-Path $ProjectDir ".build-venv"
$Python = Join-Path $BuildVenv "Scripts\python.exe"
$BuildSecrets = Join-Path $ProjectDir "coreinsight_local_toolkit\_build_secrets.py"
$env:PYINSTALLER_CONFIG_DIR = Join-Path $ProjectDir ".pyinstaller-cache"
$env:PIP_CACHE_DIR = Join-Path $ProjectDir ".pip-cache"

if ([string]::IsNullOrWhiteSpace($env:COREINSIGHT_DRAFT_DB_USER)) {
    throw "Missing build environment variable: COREINSIGHT_DRAFT_DB_USER"
}
if ([string]::IsNullOrWhiteSpace($env:COREINSIGHT_DRAFT_DB_PASSWORD)) {
    throw "Missing build environment variable: COREINSIGHT_DRAFT_DB_PASSWORD"
}

$DraftDbUserLiteral = ConvertTo-Json ([string]$env:COREINSIGHT_DRAFT_DB_USER) -Compress
$DraftDbPasswordLiteral = ConvertTo-Json ([string]$env:COREINSIGHT_DRAFT_DB_PASSWORD) -Compress
$BuildSecretsContent = @"
# Generated by build.ps1 from the build machine environment. Do not commit.
DRAFT_DB_USER = $DraftDbUserLiteral
DRAFT_DB_PASSWORD = $DraftDbPasswordLiteral
"@
[System.IO.File]::WriteAllText(
    $BuildSecrets,
    $BuildSecretsContent,
    [System.Text.UTF8Encoding]::new($false)
)

Push-Location $ProjectDir
try {
    if (-not (Test-Path -LiteralPath $Python)) {
        python -m venv $BuildVenv
    }

    & $Python -m pip install --disable-pip-version-check -r (Join-Path $ProjectDir "requirements-build.txt")
    & $Python -m PyInstaller --noconfirm --clean (Join-Path $ProjectDir "coreinsight-local-toolkit.spec")

    $Exe = Join-Path $ProjectDir "dist\coreinsight-local-toolkit.exe"
    if (-not (Test-Path -LiteralPath $Exe)) {
        throw "Build completed without expected executable: $Exe"
    }
} finally {
    if (Test-Path -LiteralPath $BuildSecrets) {
        Remove-Item -LiteralPath $BuildSecrets -Force
    }
    Pop-Location
}

Write-Host "Built: $Exe"
