const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={groups:[],activeId:'',messages:[],cursor:'',hasMore:false,totalHint:0,selectionMode:'all',excluded:new Set(),included:new Set(),loading:false,extractTask:{status:'idle',running:false}};

async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json','X-CoreInsight-Protocol':'1'},...options});if(!response.ok){let message=`请求失败 (${response.status})`;try{const body=await response.json();message=body.detail||message}catch{}throw new Error(message)}return response.status===204?null:response.json()}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add('hidden'),2800)}
function active(){return state.groups.find(group=>group.groupId===state.activeId)}
function localValue(date){const offset=date.getTimezoneOffset()*60000;return new Date(date-offset).toISOString().slice(0,16)}
function rangeValues(range){const now=new Date();if(range==='all')return['',''];if(range==='custom')return[$('#start-time').value,$('#end-time').value];const end=localValue(now);let start=new Date(now);if(range==='today')start.setHours(0,0,0,0);else start.setDate(start.getDate()-Number(range[0]));return[localValue(start),end]}
function messageType(value){return({TEXT_MSG:'文本',PICTURE_MSG:'图片',FILE_MSG:'文件',CARD_MSG:'卡片',NOTICE_MSG:'通知'})[value]||value||'未知'}

function renderGroups(){const list=$('#group-list');list.innerHTML='';$('#group-count').textContent=`${state.groups.length} 个群组`;$('#group-empty').classList.toggle('hidden',state.groups.length>0);for(const group of state.groups){const item=document.createElement('div');item.className=`group-item${group.groupId===state.activeId?' active':''}`;item.innerHTML=`<i class="dot ${group.status}"></i><div><b></b><small></small></div>`;item.querySelector('b').textContent=group.name||group.groupId;item.querySelector('small').textContent=group.groupId;item.onclick=()=>selectGroup(group.groupId);list.appendChild(item)}}
function selectGroup(groupId){state.activeId=groupId;state.messages=[];resetSelection();renderGroups();fillConfig()}
function fillConfig(){const group=active();$('#blank-state').classList.toggle('hidden',!!group);$('#config-form').classList.toggle('hidden',!group);if(!group)return;$('#config-title').textContent=group.name||group.groupId;$('#group-id').value=group.groupId;$('#group-name').value=group.name||'';$('#prompt-content').value=group.promptContent||'';$('#start-time').value=(group.startTime||'').slice(0,16);$('#end-time').value=(group.endTime||'').slice(0,16);const method=$(`input[name="method"][value="${group.extractMethod}"]`);if(method&&!method.disabled)method.checked=true;$(`input[name="mode"][value="${group.extractMode}"]`).checked=true;const range=group.quickRange||'7d';setRange(range,range!=='all'&&range!=='custom'&&!group.startTime&&!group.endTime);const labels={idle:'空闲',extracting:'提取中',scheduled:'已定时'};$('#status-pill').textContent=labels[group.status]||'空闲';$('#cancel-schedule').classList.toggle('hidden',!group.scheduleEnabled);$('#schedule-button').textContent=group.scheduleEnabled?'修改定时':'定时提取';$('#preview-summary').textContent='查看群组消息，取消勾选不需要提取的内容'}
function setRange(range,update=true){$$('[data-range]').forEach(button=>button.classList.toggle('active',button.dataset.range===range));if(update){const [start,end]=rangeValues(range);$('#start-time').value=start;$('#end-time').value=end}const group=active();if(group)group.quickRange=range}
function formPayload(){const group=active();return{...group,name:$('#group-name').value.trim(),startTime:$('#start-time').value,endTime:$('#end-time').value,quickRange:$('.range-buttons .active')?.dataset.range||'custom',extractMethod:$('input[name="method"]:checked').value,extractMode:$('input[name="mode"]:checked').value,promptContent:$('#prompt-content').value}}

async function loadGroups(){try{state.groups=await api('/welink/group/list');if(state.activeId&&!state.groups.some(g=>g.groupId===state.activeId))state.activeId='';if(!state.activeId&&state.groups.length)state.activeId=state.groups[0].groupId;renderGroups();fillConfig()}catch(error){toast(error.message,true)}}
async function addGroup(event){event.preventDefault();const groupId=$('#new-group-id').value.trim();if(!groupId)return toast('请输入群组 ID',true);try{const group=await api('/welink/group/add',{method:'POST',body:JSON.stringify({groupId,name:$('#new-group-name').value.trim()})});state.groups.push(group);state.activeId=group.groupId;$('#add-form').reset();$('#add-form').classList.add('hidden');renderGroups();fillConfig();toast('群组已添加')}catch(error){toast(error.message,true)}}
async function saveConfig(event){event.preventDefault();try{const group=await api('/welink/group/update',{method:'PUT',body:JSON.stringify(formPayload())});state.groups=state.groups.map(item=>item.groupId===group.groupId?group:item);renderGroups();fillConfig();toast('配置已保存')}catch(error){toast(error.message,true)}}
async function deleteGroup(){const group=active();if(!group||!confirm(`确定删除“${group.name||group.groupId}”吗？\n这不会删除 WeLink 中的原始消息。`))return;try{await api('/welink/group/delete',{method:'DELETE',body:JSON.stringify({groupId:group.groupId})});state.groups=state.groups.filter(item=>item.groupId!==group.groupId);state.activeId=state.groups[0]?.groupId||'';renderGroups();fillConfig();toast('群组已删除')}catch(error){toast(error.message,true)}}

function renderExtractTask(){const task=state.extractTask||{},button=$('#extract-button'),progress=$('#extract-progress');button.classList.toggle('cancel',!!task.running);button.disabled=false;button.innerHTML=task.running?'取消提取 <span>×</span>':'提取 <span>→</span>';const counts=task.scanned?` · 扫描 ${task.scanned} / 选中 ${task.selected}`:'';progress.textContent=(task.message||'')+counts;const labels={fetching:'读取中',markdown:'整理中',llm:'模型提取中',pushing:'经验入库中',done:'已完成',failed:'失败',cancelled:'已取消',idle:'空闲'};$('#status-pill').textContent=labels[task.status]||task.status||'空闲';if(task.error)progress.textContent=task.error}
async function waitExtractStopped(){for(let i=0;i<40;i++){state.extractTask=await api('/welink/extract/status');if(!state.extractTask.running)return;await new Promise(resolve=>setTimeout(resolve,250))}throw new Error('当前提取尚未停止，请稍后重试')}
async function startOrCancelExtract(){const group=active();if(!group)return;if(state.extractTask?.running){if(!confirm('正在提取中，是否中断并按当前配置重新提取？'))return;try{await api('/welink/extract/cancel',{method:'POST',body:'{}'});await waitExtractStopped()}catch(error){return toast(error.message,true)}}const config=formPayload();if(config.extractMode==='draft')return toast('草稿审核尚未实现，请先选择直接入库',true);try{if(group.scheduleEnabled){if(!confirm('已设定定时提取，手动提取将取消定时任务，是否继续？'))return;await api('/welink/schedule/cancel',{method:'POST',body:JSON.stringify({groupId:group.groupId})});group.scheduleEnabled=false;group.status='idle';fillConfig()}const endTime=config.endTime||localValue(new Date());const payload={groupId:group.groupId,startTime:config.startTime||null,endTime,extractMethod:config.extractMethod,extractMode:config.extractMode,promptContent:config.promptContent,selection:selectionPayload()};state.extractTask=await api('/welink/extract',{method:'POST',body:JSON.stringify(payload)});renderExtractTask();toast('本地聊天记录提取任务已启动')}catch(error){toast(error.message,true)}}
async function pollExtract(){try{const previous=state.extractTask?.status;state.extractTask=await api('/welink/extract/status');if(state.extractTask.running&&state.extractTask.groupId){const group=state.groups.find(item=>item.groupId===state.extractTask.groupId);if(group)group.status='extracting';renderGroups()}renderExtractTask();if(previous&&previous!==state.extractTask.status&&!state.extractTask.running)await loadGroups();if(previous&&previous!==state.extractTask.status&&state.extractTask.status==='done')toast(state.extractTask.message||'经验提取并入库完成');if(previous&&previous!==state.extractTask.status&&state.extractTask.status==='failed')toast(state.extractTask.error||'提取失败',true)}catch{}}

function toggleScheduleFields(){const custom=$('#schedule-freq').value==='custom';$('#schedule-time-wrap').classList.toggle('hidden',custom);$('#schedule-cron-wrap').classList.toggle('hidden',!custom)}
function closeSchedule(){$('#schedule-modal').classList.add('hidden')}
async function openSchedule(){const group=active();if(!group)return;if(state.extractTask?.running&&state.extractTask.groupId===group.groupId){if(!confirm('正在提取中，设定定时任务将中断当前提取，是否继续？'))return;try{await api('/welink/extract/cancel',{method:'POST',body:'{}'});await waitExtractStopped()}catch(error){return toast(error.message,true)}}if(group.scheduleEnabled&&!confirm('已设定定时提取，是否修改定时配置？'))return;$('#schedule-freq').value=group.scheduleFreq||'daily';$('#schedule-time').value=group.scheduleTime||'09:00:00';$('#schedule-cron').value=group.scheduleCron||'';$('#schedule-note').textContent=group.scheduleNextRun?`下次执行：${group.scheduleNextRun.replace('T',' ')}`:'首次保存后，从当前时间开始记录新增消息。';toggleScheduleFields();$('#schedule-modal').classList.remove('hidden')}
async function saveSchedule(event){event.preventDefault();const group=active();if(!group)return;const config=formPayload();const payload={groupId:group.groupId,extractMethod:'prompt',extractMode:'direct',promptContent:config.promptContent,scheduleFreq:$('#schedule-freq').value,scheduleTime:$('#schedule-time').value||'09:00:00',scheduleCron:$('#schedule-cron').value.trim()};try{const saved=await api('/welink/schedule/set',{method:'POST',body:JSON.stringify(payload)});state.groups=state.groups.map(item=>item.groupId===saved.groupId?saved:item);fillConfig();renderGroups();closeSchedule();toast('定时任务已保存')}catch(error){toast(error.message,true)}}
async function cancelSchedule(){const group=active();if(!group||!confirm('确定取消该群组的定时提取吗？'))return;try{const saved=await api('/welink/schedule/cancel',{method:'POST',body:JSON.stringify({groupId:group.groupId})});state.groups=state.groups.map(item=>item.groupId===saved.groupId?saved:item);fillConfig();renderGroups();toast('定时任务已取消')}catch(error){toast(error.message,true)}}

function resetSelection(){state.selectionMode='all';state.excluded=new Set();state.included=new Set()}
function isSelected(id){return state.selectionMode==='all'?!state.excluded.has(id):state.included.has(id)}
function setMessageSelected(id,checked){const target=state.selectionMode==='all'?state.excluded:state.included;if(state.selectionMode==='all'){checked?target.delete(id):target.add(id)}else{checked?target.add(id):target.delete(id)}}
function selectionPayload(){return state.selectionMode==='all'?{mode:'all',excludedMessageIds:[...state.excluded]}:{mode:'explicit',selectedMessageIds:[...state.included]}}
function openPreview(){const group=active();if(!group)return;$('#preview-modal').classList.remove('hidden');$('#modal-title').textContent=`${group.name||group.groupId} · 消息预览`;loadMessages(true)}
function closePreview(){$('#preview-modal').classList.add('hidden')}
async function loadMessages(reset=false){const group=active();if(!group||state.loading)return;if(reset){state.messages=[];state.cursor='';state.hasMore=false;state.totalHint=0;resetSelection()}state.loading=true;renderCount();$('#message-loading').classList.remove('hidden');if(reset){$('#message-empty').classList.add('hidden');$('#message-table').classList.add('hidden')}const startTime=$('#start-time').value||null,endTime=$('#end-time').value||null;$('#modal-range').textContent=startTime||endTime?`${startTime?.replace('T',' ')||'最早'} 至 ${endTime?.replace('T',' ')||'现在'}`:'WeLink 当前账号可读取的全部历史';try{const page=await api('/welink/message/page',{method:'POST',body:JSON.stringify({groupId:group.groupId,startTime,endTime,cursor:state.cursor,limit:100})});const known=new Set(state.messages.map(item=>item.id));state.messages.push(...page.items.filter(item=>!known.has(item.id)));state.cursor=page.nextCursor||'';state.hasMore=!!page.hasMore;state.totalHint=Math.max(state.totalHint,page.totalHint||0)}catch(error){if(reset)state.messages=[];toast(error.message,true)}finally{state.loading=false;$('#message-loading').classList.add('hidden');renderMessages()}}
function renderMessages(){const body=$('#message-body');body.innerHTML='';$('#message-empty').classList.toggle('hidden',state.messages.length>0);$('#message-table').classList.toggle('hidden',!state.messages.length);for(const message of state.messages){const row=document.createElement('tr');row.innerHTML='<td><input type="checkbox"></td><td></td><td></td><td></td><td class="message-content"></td>';const check=row.querySelector('input');check.checked=isSelected(message.id);check.onchange=()=>{setMessageSelected(message.id,check.checked);renderCount()};const cells=row.querySelectorAll('td');cells[1].textContent=(message.time||'').replace('T',' ');cells[2].textContent=message.sender||'-';cells[3].textContent=messageType(message.contentType);cells[4].textContent=message.content||'';body.appendChild(row)}renderCount()}
function renderCount(){const selectedLoaded=state.messages.filter(item=>isSelected(item.id)).length;$('#selected-count').textContent=state.selectionMode==='all'?`范围内全选 · 排除 ${state.excluded.size} 条`:`已明确选择 ${state.included.size} 条`;$('#message-total').textContent=`已加载 ${state.messages.length} 条${state.hasMore?' · 仍有更早消息':' · 已到底'}`;$('#check-all').checked=state.selectionMode==='all'&&state.excluded.size===0;$('#check-all').indeterminate=(state.selectionMode==='all'&&state.excluded.size>0)||(state.selectionMode==='explicit'&&selectedLoaded>0);$('#load-more').classList.toggle('hidden',!state.hasMore);$('#load-more').disabled=state.loading}

function bind(){$('#show-add').onclick=()=>{$('#add-form').classList.toggle('hidden');if(!$('#add-form').classList.contains('hidden'))$('#new-group-id').focus()};$('#cancel-add').onclick=()=>$('#add-form').classList.add('hidden');$('#add-form').onsubmit=addGroup;$('#config-form').onsubmit=saveConfig;$('#delete-group').onclick=deleteGroup;$$('[data-range]').forEach(button=>button.onclick=()=>setRange(button.dataset.range));$('#start-time').onchange=$('#end-time').onchange=()=>setRange('custom',false);$('#preview-button').onclick=openPreview;$('#close-preview').onclick=closePreview;$('#preview-modal').onclick=event=>{if(event.target===$('#preview-modal'))closePreview()};$('#refresh-preview').onclick=()=>loadMessages(true);$('#load-more').onclick=()=>loadMessages(false);$('#check-all').onchange=event=>{if(event.target.checked){state.selectionMode='all';state.excluded.clear();state.included.clear()}else{state.selectionMode='explicit';state.included.clear();state.excluded.clear()}renderMessages()};$('#confirm-preview').onclick=()=>{const selection=selectionPayload();$('#preview-summary').textContent=selection.mode==='all'?`范围内全部消息（排除 ${selection.excludedMessageIds.length} 条）`:`已选择 ${selection.selectedMessageIds.length} 条消息`;closePreview();toast('消息选择条件已保留')};$('#extract-button').onclick=startOrCancelExtract;$('#schedule-button').onclick=openSchedule;$('#cancel-schedule').onclick=cancelSchedule;$('#schedule-form').onsubmit=saveSchedule;$('#schedule-freq').onchange=toggleScheduleFields;$('#close-schedule').onclick=$('#schedule-back').onclick=closeSchedule;$('#schedule-modal').onclick=event=>{if(event.target===$('#schedule-modal'))closeSchedule()}}

bind();loadGroups();pollExtract();setInterval(pollExtract,2000);
