const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={groups:[],activeId:'',messages:[],selected:new Set()};

async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json','X-CoreInsight-Protocol':'1'},...options});if(!response.ok){let message=`请求失败 (${response.status})`;try{const body=await response.json();message=body.detail||message}catch{}throw new Error(message)}return response.status===204?null:response.json()}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast${error?' error':''}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.add('hidden'),2800)}
function active(){return state.groups.find(group=>group.groupId===state.activeId)}
function localValue(date){const offset=date.getTimezoneOffset()*60000;return new Date(date-offset).toISOString().slice(0,16)}
function rangeValues(range){const now=new Date();if(range==='all')return['',''];if(range==='custom')return[$('#start-time').value,$('#end-time').value];const end=localValue(now);let start=new Date(now);if(range==='today')start.setHours(0,0,0,0);else start.setDate(start.getDate()-Number(range[0]));return[localValue(start),end]}
function messageType(value){return({TEXT_MSG:'文本',PICTURE_MSG:'图片',FILE_MSG:'文件',CARD_MSG:'卡片',NOTICE_MSG:'通知'})[value]||value||'未知'}

function renderGroups(){const list=$('#group-list');list.innerHTML='';$('#group-count').textContent=`${state.groups.length} 个群组`;$('#group-empty').classList.toggle('hidden',state.groups.length>0);for(const group of state.groups){const item=document.createElement('div');item.className=`group-item${group.groupId===state.activeId?' active':''}`;item.innerHTML=`<i class="dot ${group.status}"></i><div><b></b><small></small></div>`;item.querySelector('b').textContent=group.name||group.groupId;item.querySelector('small').textContent=group.groupId;item.onclick=()=>selectGroup(group.groupId);list.appendChild(item)}}
function selectGroup(groupId){state.activeId=groupId;state.messages=[];state.selected.clear();renderGroups();fillConfig()}
function fillConfig(){const group=active();$('#blank-state').classList.toggle('hidden',!!group);$('#config-form').classList.toggle('hidden',!group);if(!group)return;$('#config-title').textContent=group.name||group.groupId;$('#group-id').value=group.groupId;$('#group-name').value=group.name||'';$('#prompt-content').value=group.promptContent||'';$('#start-time').value=(group.startTime||'').slice(0,16);$('#end-time').value=(group.endTime||'').slice(0,16);const method=$(`input[name="method"][value="${group.extractMethod}"]`);if(method&&!method.disabled)method.checked=true;$(`input[name="mode"][value="${group.extractMode}"]`).checked=true;const range=group.quickRange||'7d';setRange(range,range!=='all'&&range!=='custom'&&!group.startTime&&!group.endTime);const labels={idle:'空闲',extracting:'提取中',scheduled:'已定时'};$('#status-pill').textContent=labels[group.status]||'空闲';$('#preview-summary').textContent='查看群组消息，取消勾选不需要提取的内容'}
function setRange(range,update=true){$$('[data-range]').forEach(button=>button.classList.toggle('active',button.dataset.range===range));if(update){const [start,end]=rangeValues(range);$('#start-time').value=start;$('#end-time').value=end}const group=active();if(group)group.quickRange=range}
function formPayload(){const group=active();return{...group,name:$('#group-name').value.trim(),startTime:$('#start-time').value,endTime:$('#end-time').value,quickRange:$('.range-buttons .active')?.dataset.range||'custom',extractMethod:$('input[name="method"]:checked').value,extractMode:$('input[name="mode"]:checked').value,promptContent:$('#prompt-content').value}}

async function loadGroups(){try{state.groups=await api('/welink/group/list');if(state.activeId&&!state.groups.some(g=>g.groupId===state.activeId))state.activeId='';if(!state.activeId&&state.groups.length)state.activeId=state.groups[0].groupId;renderGroups();fillConfig()}catch(error){toast(error.message,true)}}
async function addGroup(event){event.preventDefault();const groupId=$('#new-group-id').value.trim();if(!groupId)return toast('请输入群组 ID',true);try{const group=await api('/welink/group/add',{method:'POST',body:JSON.stringify({groupId,name:$('#new-group-name').value.trim()})});state.groups.push(group);state.activeId=group.groupId;$('#add-form').reset();$('#add-form').classList.add('hidden');renderGroups();fillConfig();toast('群组已添加')}catch(error){toast(error.message,true)}}
async function saveConfig(event){event.preventDefault();try{const group=await api('/welink/group/update',{method:'PUT',body:JSON.stringify(formPayload())});state.groups=state.groups.map(item=>item.groupId===group.groupId?group:item);renderGroups();fillConfig();toast('配置已保存')}catch(error){toast(error.message,true)}}
async function deleteGroup(){const group=active();if(!group||!confirm(`确定删除“${group.name||group.groupId}”吗？\n这不会删除 WeLink 中的原始消息。`))return;try{await api('/welink/group/delete',{method:'DELETE',body:JSON.stringify({groupId:group.groupId})});state.groups=state.groups.filter(item=>item.groupId!==group.groupId);state.activeId=state.groups[0]?.groupId||'';renderGroups();fillConfig();toast('群组已删除')}catch(error){toast(error.message,true)}}

function openPreview(){const group=active();if(!group)return;$('#preview-modal').classList.remove('hidden');$('#modal-title').textContent=`${group.name||group.groupId} · 消息预览`;loadMessages()}
function closePreview(){$('#preview-modal').classList.add('hidden')}
async function loadMessages(){const group=active();if(!group)return;$('#message-loading').classList.remove('hidden');$('#message-empty').classList.add('hidden');$('#message-table').classList.add('hidden');const startTime=$('#start-time').value||null,endTime=$('#end-time').value||null;$('#modal-range').textContent=startTime||endTime?`${startTime?.replace('T',' ')||'最早'} 至 ${endTime?.replace('T',' ')||'现在'}`:'全部历史消息';try{state.messages=await api('/welink/message/list',{method:'POST',body:JSON.stringify({groupId:group.groupId,startTime,endTime})});state.selected=new Set(state.messages.map(item=>item.id));renderMessages()}catch(error){state.messages=[];renderMessages();toast(error.message,true)}finally{$('#message-loading').classList.add('hidden')}}
function renderMessages(){const body=$('#message-body');body.innerHTML='';$('#message-empty').classList.toggle('hidden',state.messages.length>0);$('#message-table').classList.toggle('hidden',!state.messages.length);for(const message of state.messages){const row=document.createElement('tr');row.innerHTML='<td><input type="checkbox"></td><td></td><td></td><td></td><td class="message-content"></td>';const check=row.querySelector('input');check.checked=state.selected.has(message.id);check.onchange=()=>{check.checked?state.selected.add(message.id):state.selected.delete(message.id);renderCount()};const cells=row.querySelectorAll('td');cells[1].textContent=(message.time||'').replace('T',' ');cells[2].textContent=message.sender||'-';cells[3].textContent=messageType(message.contentType);cells[4].textContent=message.content||'';body.appendChild(row)}renderCount()}
function renderCount(){const count=state.selected.size,total=state.messages.length;$('#selected-count').textContent=`已选 ${count} 条`;$('#message-total').textContent=`共 ${total} 条消息`;$('#check-all').checked=total>0&&count===total;$('#check-all').indeterminate=count>0&&count<total}

function bind(){$('#show-add').onclick=()=>{$('#add-form').classList.toggle('hidden');if(!$('#add-form').classList.contains('hidden'))$('#new-group-id').focus()};$('#cancel-add').onclick=()=>$('#add-form').classList.add('hidden');$('#add-form').onsubmit=addGroup;$('#config-form').onsubmit=saveConfig;$('#delete-group').onclick=deleteGroup;$$('[data-range]').forEach(button=>button.onclick=()=>setRange(button.dataset.range));$('#start-time').onchange=$('#end-time').onchange=()=>setRange('custom',false);$('#preview-button').onclick=openPreview;$('#close-preview').onclick=closePreview;$('#preview-modal').onclick=event=>{if(event.target===$('#preview-modal'))closePreview()};$('#refresh-preview').onclick=loadMessages;$('#check-all').onchange=event=>{state.selected=event.target.checked?new Set(state.messages.map(item=>item.id)):new Set();renderMessages()};$('#confirm-preview').onclick=()=>{$('#preview-summary').textContent=`已选择 ${state.selected.size} / ${state.messages.length} 条消息`;closePreview();toast('消息选择已保留')};$$('.disabled-action').forEach(button=>button.onclick=()=>toast('该能力将在下一阶段接入'))}

bind();loadGroups();
