const state={settings:{},serverPresets:[],configured:false,emails:[],selected:new Set(),ruleFilterActive:false,search:'',page:1,pageSize:50,rules:[],blacklist:[],ruleKind:'rules',emailTask:{running:false},emailSchedule:{active:false},welinkSources:[],welinkChecked:new Set(),welinkActive:'',welinkViews:{},welinkTask:{running:false},welinkSchedule:{active:false},eventCursor:0,foldersLoaded:false,confirmedUserId:'',mandatorySetup:false,updateInfo:{},ruleBackup:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const splitList=v=>String(v||'').split(/[,，\n]/).map(x=>x.trim()).filter(Boolean);

function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast${error?' error':''}`;clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.add('hidden'),3500)}
async function call(name,...args){try{const fn=window.pywebview?.api?.[name];if(!fn)throw new Error('JS Bridge 尚未就绪');const r=await fn(...args);if(!r?.ok)throw new Error(r?.error||'未知错误');return r}catch(e){toast(e.message||String(e),true);throw e}}
function showPage(name){$$('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${name}`));$$('.nav[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===name))}
function openModal(id){$(`#${id}`).classList.remove('hidden')} function closeModal(id){if(id==='settings-modal'&&state.mandatorySetup)return;$(`#${id}`).classList.add('hidden')}
function setBusy(on){const p=$('#progress');p.classList.toggle('hidden',!on);const determinate=state.emailTask.running&&state.emailTask.total>0;p.classList.toggle('determinate',determinate);if(determinate)p.querySelector('i').style.width=`${Math.min(100,state.emailTask.current/state.emailTask.total*100)}%`;else p.querySelector('i').style.width='32%';$('#refresh-emails').disabled=on||state.emailTask.running}

// ── email table ─────────────────────────────────────────────────
function filteredEmails(){const q=state.search.trim().toLowerCase();return state.emails.filter(x=>(!state.ruleFilterActive||x.matched_rule)&&(!q||`${x.matched_rule} ${x.subject} ${x.sender_name} ${x.sender_email} ${x.conversation_topic}`.toLowerCase().includes(q)))}
function statusBadge(raw){const text=raw||'-',cls=text==='已解析'?'done':text==='解析失败'?'failed':text==='解析中'?'pending':'none';return `<span class="badge ${cls}">${esc(text)}</span>`}
function updateRuleFilterButton(){$('#shared-rule-toggle span').textContent='按规则匹配';$('#rule-filter-enabled').checked=state.ruleFilterActive;$('#shared-rule-toggle').classList.toggle('active',state.ruleFilterActive)}
function openSharedRules(){state.ruleBackup={rules:structuredClone(state.rules),blacklist:structuredClone(state.blacklist)};state.ruleKind='rules';$$('[data-rule-kind]').forEach(x=>x.classList.toggle('active',x.dataset.ruleKind==='rules'));renderRules();$('#shared-rule-popover').classList.remove('hidden')}
function cancelSharedRules(){if(state.ruleBackup){state.rules=state.ruleBackup.rules;state.blacklist=state.ruleBackup.blacklist;state.ruleBackup=null}$('#shared-rule-popover').classList.add('hidden')}
async function saveSharedRules(){collectRules();const button=$('#save-rule-filter');button.disabled=true;button.textContent='保存中…';try{const white=await call('save_rules','rules',state.rules),black=await call('save_rules','blacklist',state.blacklist);state.rules=white.items;state.blacklist=black.items;state.ruleBackup=null;$('#shared-rule-popover').classList.add('hidden');await refreshEmails();toast('规则已保存')}finally{button.disabled=false;button.textContent='保存规则'}}
function renderEmails(){const filtered=filteredEmails(),pages=Math.max(1,Math.ceil(filtered.length/state.pageSize));state.page=Math.max(1,Math.min(state.page,pages));const start=(state.page-1)*state.pageSize,rows=filtered.slice(start,start+state.pageSize);$('#email-col-0').className='check';$('#email-col-0').innerHTML='<input type="checkbox" id="check-all">';$('#email-col-1').className='number';$('#email-col-1').textContent='#';$('#email-body').innerHTML=rows.length?rows.map((x,i)=>`<tr><td><input class="email-check" type="checkbox" data-id="${esc(x.item_id)}" ${state.selected.has(x.item_id)?'checked':''}></td><td>${start+i+1}</td><td>${statusBadge(x.parseStatus)}</td><td>${esc((x.received_time||'').replace('T',' '))}</td><td title="${esc(x.sender_email)}">${esc(x.sender_name||x.sender_email)}</td><td title="${esc(x.subject)}">${esc(x.subject)}</td><td title="${esc(x.conversation_topic)}">${esc(x.conversation_topic)}</td></tr>`).join(''):`<tr><td colspan="7" class="empty"><div class="empty-state"><span>⌕</span><b>没有符合条件的邮件</b><small>尝试修改搜索关键词或规则</small></div></td></tr>`;$('#page-info').textContent=`第 ${state.page} / ${pages} 页`;$('#total-info').textContent=`共 ${filtered.length} 封`;$('#first-page').disabled=$('#prev-page').disabled=state.page<=1;$('#last-page').disabled=$('#next-page').disabled=state.page>=pages;const ids=filtered.map(x=>x.item_id),check=$('#check-all');check.checked=!!ids.length&&ids.every(id=>state.selected.has(id));check.onchange=e=>{filteredEmails().forEach(x=>e.target.checked?state.selected.add(x.item_id):state.selected.delete(x.item_id));renderEmails()};$$('.email-check').forEach(box=>box.onchange=()=>{box.checked?state.selected.add(box.dataset.id):state.selected.delete(box.dataset.id);renderEmails()});const n=state.selected.size;$('#start-selected-count').textContent=`当前选中 ${n} 封邮件`;$('#start-selected-option').disabled=!n;const b=$('#open-start');if(state.emailTask.running){b.innerHTML=`停止处理 ${state.emailTask.current||0}/${state.emailTask.total||0}`;b.classList.add('danger')}else{b.innerHTML='<span class="button-icon">▶</span>启动<span class="start-caret"></span>';b.classList.remove('danger')}updateRuleFilterButton()}
async function refreshEmails(){setBusy(true);try{const r=await call('list_emails');state.emails=r.items;state.selected.clear();state.page=1;renderEmails();await fetchPageStatus();if(!state.foldersLoaded){state.foldersLoaded=true;await refreshFolders()}}finally{setBusy(false)}}
async function fetchPageStatus(){if(!state.settings.namespace||String(state.settings.backendUrl).toLowerCase()==='offline')return;const rows=filteredEmails().slice((state.page-1)*state.pageSize,state.page*state.pageSize),topics=rows.map(x=>x.conversation_topic).filter(Boolean);if(!topics.length)return;try{const r=await call('parse_status',topics),map=r.items||{};state.emails.forEach(x=>{const raw=map[(x.conversation_topic||'').trim()];if(raw)x.parseStatus={done:'已解析',failed:'解析失败',pending:'解析中'}[raw]||raw});renderEmails()}catch(_){}}
async function processSelected(){$('#start-menu').classList.add('hidden');if(state.emailTask.running){await call('cancel_email_processing');return}if(!state.selected.size)return;if(!confirm(`将选中的 ${state.selected.size} 封邮件推送到服务端处理（已解析邮件也会重新解析）。\n未命中规则的邮件将标记为“手动处理”。\n\n确定继续？`))return;const r=await call('start_email_processing',[...state.selected]);state.emailTask=r.task;renderEmails();setBusy(true)}

// ── Outlook folders ─────────────────────────────────────────────
async function refreshFolders(){const box=$('#folder-list');box.innerHTML='<div class="empty small">正在读取 Outlook…</div>';try{const r=await call('list_folders'),selected=new Set(state.settings.scanFolders||[]);box.innerHTML=r.items.map(path=>{const depth=path.split('\\').length-1,name=path.split('\\').pop();return `<label class="folder" style="padding-left:${7+depth*14}px" title="${esc(path)}"><input type="checkbox" value="${esc(path)}" ${selected.has(path)?'checked':''}><span>${esc(name)}</span></label>`}).join('')||'<div class="empty small">没有可用文件夹</div>';$$('#folder-list input').forEach(x=>x.onchange=saveFolderSelection)}catch(e){box.innerHTML=`<div class="empty small">加载失败：${esc(e.message)}</div>`;state.foldersLoaded=false}}
async function saveFolderSelection(){state.settings.scanFolders=$$('#folder-list input:checked').map(x=>x.value).sort();try{const r=await call('save_settings',state.settings);state.settings=r.settings;await refreshEmails()}catch(_){}}

// ── rules ───────────────────────────────────────────────────────
function ruleData(){return state[state.ruleKind]}
function renderRules(){$('#email-rules').innerHTML=ruleData().map((r,i)=>`<div class="email-rule" data-index="${i}"><input data-key="name" value="${esc(r.name)}" placeholder="规则名称"><input data-key="keywords" value="${esc((r.keywords||[]).join(', '))}" placeholder="逗号分隔"><input data-key="body_keywords" value="${esc((r.body_keywords||[]).join(', '))}" placeholder="逗号分隔"><input data-key="senders" value="${esc((r.senders||[]).join(', '))}" placeholder="姓名或邮箱"><select data-key="logic"><option value="OR" ${r.logic!=='AND'?'selected':''}>或</option><option value="AND" ${r.logic==='AND'?'selected':''}>且</option></select><button class="remove danger" data-remove-rule="${i}">×</button></div>`).join('')||'<div class="empty small">暂无规则</div>';$$('[data-remove-rule]').forEach(b=>b.onclick=()=>{const r=ruleData()[Number(b.dataset.removeRule)];if(confirm(`确定删除${state.ruleKind==='blacklist'?'黑名单':'规则'}“${r.name||'未命名'}”？`)){ruleData().splice(Number(b.dataset.removeRule),1);renderRules()}})}
function collectRules(){$$('.email-rule').forEach(row=>{const r=ruleData()[Number(row.dataset.index)];row.querySelectorAll('[data-key]').forEach(el=>{const k=el.dataset.key;r[k]=['keywords','body_keywords','senders'].includes(k)?splitList(el.value):el.value})})}
// ── email scheduler ─────────────────────────────────────────────
function updateSchedule(s){state.emailSchedule=s;const b=$('#start-timer-option');if(!b)return;b.querySelector('b').textContent=s.active?'停止定时':'启动定时';b.querySelector('span').textContent=s.active?`下次执行：${s.nextRun||'-'}`:'使用已保存的匹配规则与黑名单';b.classList.toggle('danger',s.active)}
function updateTimerRuleSummary(){$('#timer-rule-summary').textContent=`${state.rules.length} 条匹配规则 · ${state.blacklist.length} 条黑名单`}
function openStart(){if(state.emailTask.running){call('cancel_email_processing');return}$('#start-selected-count').textContent=`当前选中 ${state.selected.size} 封邮件`;$('#start-selected-option').disabled=!state.selected.size;updateSchedule(state.emailSchedule);$('#start-menu').classList.toggle('hidden')}
async function chooseTimer(){$('#start-menu').classList.add('hidden');if(state.emailSchedule.active){const r=await call('stop_email_schedule');updateSchedule(r.schedule);toast('定时处理已停止');return}openTimer()}
function openTimer(){updateTimerRuleSummary();$('#timer-interval').value=state.settings.scanIntervalMinutes||60;$('#timer-daily').value=state.settings.scanDailyTime||'09:00';const mode=state.settings.scanTimerMode||'interval';$(`input[name="timer-mode"][value="${mode}"]`).checked=true;$('#timer-scope').textContent=`已加载页面保存的规则；扫描 ${(state.settings.scanFolders||[]).length} 个 Outlook 文件夹。`;openModal('timer-modal')}
async function startTimer(){const mode=$('input[name="timer-mode"]:checked').value,r=await call('start_email_schedule',mode,Number($('#timer-interval').value||60),$('#timer-daily').value||'09:00');state.settings.scanTimerMode=mode;state.settings.scanIntervalMinutes=Number($('#timer-interval').value||60);state.settings.scanDailyTime=$('#timer-daily').value||'09:00';updateSchedule(r.schedule);closeModal('timer-modal');toast('定时处理已启动')}

// ── settings ────────────────────────────────────────────────────
function backendUrl(){const select=$('#set-server-preset');return select.value==='__manual__'?$('#set-backend').value.trim():select.value}
function fillSettings(){const s=state.settings,current=s.backendUrl||'';$('#set-server-preset').innerHTML=state.serverPresets.map(x=>`<option value="${esc(x.value)}">${esc(x.label)}</option>`).join('')+'<option value="__manual__">手动输入 URL</option>';const preset=state.serverPresets.find(x=>x.value.replace(/\/$/,'')===current.replace(/\/$/,''));$('#set-server-preset').value=preset?preset.value:'__manual__';$('#set-backend').value=preset?'':current;$('#manual-url-row').classList.toggle('hidden',!!preset);$('#set-user').value=s.userId||'';state.confirmedUserId=s.userId||'';$('#set-output').value=s.outputDir||'';$('#set-json').value=s.customJsonConfig||'{}';setNamespaceOptions([],s.namespace||'');updateOfflineFields()}
function updateOfflineFields(){const offline=backendUrl().toLowerCase()==='offline';$('#set-user').disabled=offline;$('#set-namespace').disabled=offline;$('#refresh-namespaces').disabled=offline;if(offline)$('#settings-status').textContent='离线模式：不连接服务器，结果只保存到本地目录。'}
function setNamespaceOptions(items,current=''){const values=items.map(x=>typeof x==='string'?x:(x.name||x.value||x.namespace||''));if(current&&!values.includes(current))values.unshift(current);$('#set-namespace').innerHTML='<option value="">-- 请选择 --</option>'+values.map(v=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(v)}</option>`).join('')}
async function loadNamespaces(){const r=await call('get_namespaces',backendUrl());setNamespaceOptions(r.items,state.settings.namespace||'')}
let userTimer;async function searchUser(){clearTimeout(userTimer);state.confirmedUserId='';const q=$('#set-user').value.trim();if(!q||backendUrl().toLowerCase()==='offline')return $('#userinfo-results').classList.add('hidden');userTimer=setTimeout(async()=>{try{const r=await call('get_userinfo',q,backendUrl()),box=$('#userinfo-results');box.innerHTML=r.items.map(x=>`<button data-user-value="${esc(x.value)}">${esc(x.label)} <small>${esc(x.value)}</small></button>`).join('');box.classList.toggle('hidden',!r.items.length);$$('[data-user-value]').forEach(b=>b.onclick=()=>{state.confirmedUserId=b.dataset.userValue;$('#set-user').value=b.dataset.userValue;box.classList.add('hidden')})}catch(_){}},400)}
async function saveSettings(){try{JSON.parse($('#set-json').value||'{}')}catch(_){return toast('额外配置 JSON 格式不正确',true)}const offline=backendUrl().toLowerCase()==='offline';const payload={...state.settings,backendUrl:backendUrl(),userId:offline?$('#set-user').value.trim():state.confirmedUserId,namespace:$('#set-namespace').value,outputDir:$('#set-output').value.trim(),customJsonConfig:$('#set-json').value.trim()||'{}'};const r=await call('save_settings',payload);state.settings=r.settings;state.configured=r.configured;state.mandatorySetup=false;$('#settings-close').classList.remove('hidden');closeModal('settings-modal');toast('设置已保存');await refreshEmails()}
function showSettings(mandatory=false){state.mandatorySetup=mandatory;fillSettings();$('#settings-title').textContent=mandatory?'初始配置 — CoreMiner':'系统设置';$('#settings-close').classList.toggle('hidden',mandatory);openModal('settings-modal');if(backendUrl().toLowerCase()!=='offline')loadNamespaces()}

// ── WeLink history mining ───────────────────────────────────────
function wlKey(source){return `${source.type==='user'?'user':'group'}:${source.source_id}`}
function wlSource(key){return state.welinkSources.find(x=>wlKey(x)===key)}
function wlView(key=state.welinkActive){if(!key)return null;if(!state.welinkViews[key]){const now=new Date(),start=new Date(now);start.setHours(0,0,0,0);state.welinkViews[key]={items:[],selected:new Set(),page:1,range:'today',start:localDateTime(start),end:localDateTime(now),loaded:false,loading:false,status:''}}return state.welinkViews[key]}
function localDateTime(date){const pad=n=>String(n).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`}
function invalidateWlView(view){view.items=[];view.selected.clear();view.loaded=false;view.page=1;view.status='筛选范围已更新，点击“刷新”获取聊天记录'}
function setWlRange(range,render=true){const view=wlView();if(!view)return;const now=new Date();view.range=range;if(range==='all'){view.start='';view.end=''}else{const start=new Date(now);if(range==='today')start.setHours(0,0,0,0);else start.setDate(start.getDate()-7);view.start=localDateTime(start);view.end=localDateTime(now)}invalidateWlView(view);if(render)renderWelink()}
function fillWelink(){state.welinkChecked=new Set(state.welinkSources.filter(x=>x.enabled).map(wlKey));if(!state.welinkActive)state.welinkActive=[...state.welinkChecked][0]||'';for(const key of state.welinkChecked)wlView(key);renderWelink()}
function totalWlSelected(){let total=0;for(const key of state.welinkChecked)total+=wlView(key)?.selected.size||0;return total}
function renderSourceList(type){const box=$(`#wl-${type==='group'?'group':'user'}-sources`),rows=state.welinkSources.filter(x=>x.type===type);box.innerHTML=rows.map(source=>{const key=wlKey(source);return `<div class="chat-source ${state.welinkActive===key?'active':''}" data-wl-source="${esc(key)}"><input type="checkbox" data-wl-source-check="${esc(key)}" ${state.welinkChecked.has(key)?'checked':''}><span><b title="${esc(source.source_name)}">${esc(source.source_name)}</b><small title="${esc(source.source_id)}">${esc(source.source_id)}</small></span><button class="source-delete" data-wl-source-delete="${esc(key)}" title="删除">×</button></div>`}).join('')||`<div class="empty small">暂无${type==='group'?'群组':'用户'}</div>`;$(`#wl-${type==='group'?'group':'user'}-count`).textContent=rows.length}
function renderWelink(){renderSourceList('group');renderSourceList('user');$('#wl-source-tabs').innerHTML=[...state.welinkChecked].map(key=>{const source=wlSource(key),view=wlView(key);if(!source)return'';const badge=view.loaded?`${view.selected.size}/${view.items.length}`:'未获取';return `<button data-wl-tab="${esc(key)}" class="${key===state.welinkActive?'active':''}" title="${esc(source.source_name)}">${esc(source.source_name)}<b>${badge}</b></button>`}).join('')||'<span class="folder-tip">尚未选择聊天来源</span>';const view=wlView(),source=wlSource(state.welinkActive);$$('[data-wl-range]').forEach(x=>x.classList.toggle('active',!!view&&x.dataset.wlRange===view.range));$('#wl-start-time').value=view?.start||'';$('#wl-end-time').value=view?.end||'';$('#wl-start-time').disabled=$('#wl-end-time').disabled=!view;$('#wl-query-status').textContent=view?.loading?`正在分页获取“${source?.source_name||''}”的历史聊天…`:view?.status||'请在左侧勾选并点击一个群组或用户';$('#wl-query-status').classList.toggle('loading',!!view?.loading);renderWelinkMessages();bindWelinkDynamic()}
function renderWelinkMessages(){const view=wlView(),items=view?.items||[],pages=Math.max(1,Math.ceil(items.length/state.pageSize));if(view)view.page=Math.max(1,Math.min(view.page,pages));const page=view?.page||1,start=(page-1)*state.pageSize,rows=items.slice(start,start+state.pageSize);$('#wl-message-body').innerHTML=rows.length?rows.map((x,i)=>`<tr><td><input class="wl-message-check" type="checkbox" data-id="${esc(x.id)}" ${view.selected.has(x.id)?'checked':''}></td><td>${start+i+1}</td><td>${esc(x.time)}</td><td title="${esc(x.sender)}">${esc(x.sender)}</td><td><span class="badge none">${esc(x.contentType.replace('_MSG',''))}</span></td><td title="${esc(x.displayContent)}">${esc(x.displayContent)}</td></tr>`).join(''):`<tr><td colspan="6" class="empty"><div class="empty-state"><span>◎</span><b>${view?.loading?'正在分页获取历史记录':view?.loaded?'该范围没有聊天记录':'选择时间范围后点击“刷新”获取记录'}</b><small>${state.welinkActive?'每个群组和用户的筛选、选择及页码相互独立':'请先在左侧选择来源'}</small></div></td></tr>`;$('#wl-page-info').textContent=`第 ${page} / ${pages} 页`;$('#wl-total-info').textContent=`共 ${items.length} 条`;$('#wl-first-page').disabled=$('#wl-prev-page').disabled=page<=1;$('#wl-last-page').disabled=$('#wl-next-page').disabled=page>=pages;const check=$('#wl-check-all');check.disabled=!items.length;check.checked=!!items.length&&items.every(x=>view.selected.has(x.id));check.onchange=e=>{items.forEach(x=>e.target.checked?view.selected.add(x.id):view.selected.delete(x.id));renderWelink()};$$('.wl-message-check').forEach(x=>x.onchange=()=>{x.checked?view.selected.add(x.dataset.id):view.selected.delete(x.dataset.id);renderWelink()});const count=totalWlSelected();$('#welink-selected-count').textContent=`当前共选中 ${count} 条`;$('#welink-process-selected').disabled=!count;const task=state.welinkTask,b=$('#open-welink-start');if(task.running){b.innerHTML=`停止处理 ${task.current||0}/${task.total||0}`;b.classList.add('danger');$('#wl-progress').classList.remove('hidden')}else{b.innerHTML='<span class="button-icon">▶</span>启动<span class="start-caret"></span>';b.classList.remove('danger');$('#wl-progress').classList.add('hidden')}updateWelinkSchedule(state.welinkSchedule)}
function bindWelinkDynamic(){$$('[data-wl-source]').forEach(row=>row.onclick=e=>{if(e.target.closest('[data-wl-source-check],[data-wl-source-delete]'))return;selectWelinkSource(row.dataset.wlSource,true)});$$('[data-wl-source-check]').forEach(box=>box.onchange=()=>toggleWelinkSource(box.dataset.wlSource,box.checked));$$('[data-wl-source-delete]').forEach(b=>b.onclick=()=>deleteWelinkSource(b.dataset.wlSource));$$('[data-wl-tab]').forEach(b=>b.onclick=()=>selectWelinkSource(b.dataset.wlTab,false))}
async function persistWelinkSources(){state.welinkSources.forEach(x=>x.enabled=state.welinkChecked.has(wlKey(x)));const r=await call('save_welink_sources',state.welinkSources);state.welinkSources=r.items;if(r.schedule)updateWelinkSchedule(r.schedule);if(r.scheduleStopped)toast('聊天来源已变化，原定时任务已停止，请确认范围后重新启动');renderWelink()}
async function toggleWelinkSource(key,checked){checked?state.welinkChecked.add(key):state.welinkChecked.delete(key);if(checked){state.welinkActive=key;wlView(key)}else if(state.welinkActive===key)state.welinkActive=[...state.welinkChecked][0]||'';await persistWelinkSources()}
async function selectWelinkSource(key,ensureChecked){if(ensureChecked&&!state.welinkChecked.has(key)){state.welinkChecked.add(key);await persistWelinkSources()}state.welinkActive=key;wlView(key);renderWelink()}
async function addWelinkSource(){const type=$('#wl-source-type').value,id=$('#wl-source-id').value.trim(),name=$('#wl-source-name').value.trim();if(!id||!name)return toast('来源 ID 和显示名称均不能为空',true);const key=`${type}:${id}`;if(state.welinkSources.some(x=>wlKey(x)===key))return toast('该聊天来源已经存在',true);state.welinkSources.push({id:'',type,source_id:id,source_name:name,enabled:true});state.welinkChecked.add(key);state.welinkActive=key;await persistWelinkSources();$('#wl-source-id').value=$('#wl-source-name').value='';$('#source-add').classList.add('hidden');setWlRange('today')}
async function deleteWelinkSource(key){const source=wlSource(key);if(!source||!confirm(`只会从 CoreMiner 来源列表删除“${source.source_name}”，不会删除 WeLink 原始聊天。\n\n确定继续？`))return;state.welinkSources=state.welinkSources.filter(x=>wlKey(x)!==key);state.welinkChecked.delete(key);delete state.welinkViews[key];if(state.welinkActive===key)state.welinkActive=[...state.welinkChecked][0]||'';await persistWelinkSources()}
async function refreshWelink(){const source=wlSource(state.welinkActive),view=wlView();if(!source||!view)return toast('请先选择群组或用户',true);if(view.start&&view.end&&new Date(view.start)>new Date(view.end))return toast('开始时间不能晚于结束时间',true);view.loading=true;renderWelink();try{const start=view.start?new Date(view.start).getTime():0,end=view.end?new Date(view.end).getTime():0,r=await call('list_welink_history',source,start,end);view.items=r.items;view.selected=new Set(r.items.map(x=>x.id));view.page=1;view.loaded=true;view.status=`${source.source_name} · ${view.range==='all'?'全部历史':`${view.start.replace('T',' ')} 至 ${view.end.replace('T',' ')}`} · 已读取 ${r.items.length} 条（默认全选）`}catch(e){view.status=`${source.source_name} · 获取失败：${e.message||e}`}finally{view.loading=false;renderWelink()}}
async function processWelinkSelected(){$('#welink-start-menu').classList.add('hidden');if(state.welinkTask.running){await call('cancel_welink_processing');return}const jobs=[];for(const key of state.welinkChecked){const view=wlView(key),source=wlSource(key);if(source&&view?.selected.size)jobs.push({source,messageIds:[...view.selected]})}const count=jobs.reduce((n,x)=>n+x.messageIds.length,0);if(!count)return toast('没有选中的聊天记录',true);if(!confirm(`将按 ${jobs.length} 个独立来源处理选中的 ${count} 条聊天记录，来源之间不会合并。\n\n确定继续？`))return;const r=await call('start_welink_processing',jobs);state.welinkTask=r.task;renderWelinkMessages()}
function openWelinkStart(){if(state.welinkTask.running){call('cancel_welink_processing');return}$('#welink-start-menu').classList.toggle('hidden')}
function updateWelinkSchedule(schedule){state.welinkSchedule=schedule||{active:false};const b=$('#welink-schedule-option');if(!b)return;b.querySelector('b').textContent=state.welinkSchedule.active?'停止定时':'启动定时';b.querySelector('span').textContent=state.welinkSchedule.active?`下次执行：${state.welinkSchedule.nextRun||'-'}`:'按来源独立执行';b.classList.toggle('danger',state.welinkSchedule.active)}
async function chooseWelinkSchedule(){$('#welink-start-menu').classList.add('hidden');if(state.welinkSchedule.active){const r=await call('stop_welink_schedule');updateWelinkSchedule(r.schedule);return toast('聊天记录定时处理已停止')}if(!state.welinkChecked.size)return toast('请至少勾选一个群组或用户',true);$('#wl-timer-interval').value=state.settings.welinkScheduleInterval||60;$('#wl-timer-daily').value=state.settings.welinkScheduleDailyTime||'02:00';$(`input[name="wl-timer-mode"][value="${state.settings.welinkScheduleMode||'interval'}"]`).checked=true;$(`input[name="wl-schedule-range"][value="${state.settings.welinkScheduleRangeMode||'incremental'}"]`).checked=true;$('#welink-timer-summary').textContent=[...state.welinkChecked].map(key=>wlSource(key)?.source_name).filter(Boolean).join('、');openModal('welink-timer-modal')}
async function startWelinkTimer(){const sources=[...state.welinkChecked].map(wlSource).filter(Boolean),mode=$('input[name="wl-timer-mode"]:checked').value,range=$('input[name="wl-schedule-range"]:checked').value,interval=Number($('#wl-timer-interval').value||60),daily=$('#wl-timer-daily').value||'02:00',r=await call('start_welink_schedule',sources,mode,interval,daily,range);Object.assign(state.settings,{welinkScheduleMode:mode,welinkScheduleInterval:interval,welinkScheduleDailyTime:daily,welinkScheduleRangeMode:range});updateWelinkSchedule(r.schedule);closeModal('welink-timer-modal');toast(`定时处理已启动（${range==='full'?'全量':'增量'}）`)}

// ── event polling / update ──────────────────────────────────────
async function poll(){try{const [r,emailStatus,welinkStatus]=await Promise.all([call('poll_events',state.eventCursor),call('email_task_status'),call('welink_task_status')]);state.eventCursor=r.cursor;for(const e of r.events){if(e.type==='email_complete'&&e.refresh)setTimeout(refreshEmails,500);if(e.type==='welink_complete')toast(e.message,!!e.failed)}state.emailTask=emailStatus.task;updateSchedule(emailStatus.schedule);setBusy(emailStatus.task.running);renderEmails();state.welinkTask=welinkStatus.task;updateWelinkSchedule(welinkStatus.schedule);renderWelinkMessages()}catch(_){}}
function semver(v){return String(v||'0').split('.').slice(0,3).map(x=>Number(x)||0)} function older(a,b){const x=semver(a),y=semver(b);for(let i=0;i<3;i++){if(x[i]!==y[i])return x[i]<y[i]}return false}
async function checkVersion(){try{const r=await call('version_info'),info=r.info||{};if(!info.latest||!older($('#version').textContent.slice(1),info.latest))return;const force=info.min&&older($('#version').textContent.slice(1),info.min);state.updateInfo={...info,force};$('#update-content').textContent=`发现新版本 ${info.latest}（当前 ${$('#version').textContent.slice(1)}）。${info.notes?'\n\n'+info.notes:''}${force?'\n\n这是强制更新，请更新后再使用。':''}`;$('#update-later').classList.toggle('hidden',!!force&&!!info.url);openModal('update-modal')}catch(_){}}

function bind(){
  $$('.nav[data-page]').forEach(x=>x.onclick=()=>showPage(x.dataset.page));$$('[data-close]').forEach(x=>x.onclick=()=>closeModal(x.dataset.close));
  $('#open-settings').onclick=()=>showSettings(false);$('#set-server-preset').onchange=()=>{$('#manual-url-row').classList.toggle('hidden',$('#set-server-preset').value!=='__manual__');updateOfflineFields();loadNamespaces()};$('#set-backend').onchange=()=>{updateOfflineFields();loadNamespaces()};$('#set-user').oninput=searchUser;$('#refresh-namespaces').onclick=loadNamespaces;$('#test-server').onclick=async()=>{const s=$('#settings-status');s.textContent='测试中…';const r=await call('test_server',backendUrl());s.textContent=r.offline?'离线模式不连接服务器。':r.reachable?'连接成功 ✓':'连接失败，请检查服务器地址';if(r.reachable&&!r.offline)await loadNamespaces()};$('#choose-output').onclick=async()=>{const r=await call('choose_output_dir');if(r.path)$('#set-output').value=r.path};$('#save-settings').onclick=saveSettings;$('#open-manual').onclick=()=>call('open_external','https://openx.huawei.com/ProblemLocating/overview');
  let clicks=[];$('#set-json').onmousedown=()=>{const now=Date.now();clicks=[...clicks.filter(x=>now-x<800),now];if(clicks.length>=3&&state.mandatorySetup){state.mandatorySetup=false;closeModal('settings-modal')}};
  $('#refresh-emails').onclick=refreshEmails;$('#refresh-folders').onclick=refreshFolders;$('#email-search').oninput=e=>{state.search=e.target.value;state.page=1;renderEmails()};$('#rule-filter-enabled').onchange=e=>{state.ruleFilterActive=e.target.checked;state.page=1;updateRuleFilterButton();renderEmails();fetchPageStatus()};$('#shared-rule-toggle').onclick=()=>$('#shared-rule-popover').classList.contains('hidden')?openSharedRules():cancelSharedRules();$('#close-shared-rule').onclick=cancelSharedRules;$('#save-rule-filter').onclick=saveSharedRules;$('#first-page').onclick=()=>{state.page=1;renderEmails();fetchPageStatus()};$('#prev-page').onclick=()=>{state.page--;renderEmails();fetchPageStatus()};$('#next-page').onclick=()=>{state.page++;renderEmails();fetchPageStatus()};$('#last-page').onclick=()=>{state.page=Math.max(1,Math.ceil(filteredEmails().length/state.pageSize));renderEmails();fetchPageStatus()};
  $$('[data-rule-kind]').forEach(x=>x.onclick=()=>{collectRules();state.ruleKind=x.dataset.ruleKind;$$('[data-rule-kind]').forEach(y=>y.classList.toggle('active',y===x));renderRules()});$('#add-email-rule').onclick=()=>{collectRules();ruleData().push({id:'',name:'',keywords:[],body_keywords:[],senders:[],logic:'OR'});renderRules()};$('#rule-help').onclick=()=>alert(state.ruleKind==='rules'?'命中任一条规则的邮件会被处理。OR 表示任一类命中；AND 表示已配置的各类都命中。关键词使用 Outlook 搜索。':'命中规则后又命中黑名单的邮件会被排除。最终处理集合 = 匹配规则 − 黑名单。');
  $('#open-start').onclick=openStart;$('#start-selected-option').onclick=processSelected;$('#start-timer-option').onclick=chooseTimer;$('#start-timer').onclick=startTimer;document.addEventListener('click',e=>{if(!e.target.closest('.start-control')){$('#start-menu').classList.add('hidden');$('#welink-start-menu').classList.add('hidden')}});
  $('#show-source-add').onclick=()=>$('#source-add').classList.toggle('hidden');$('#cancel-source-add').onclick=()=>$('#source-add').classList.add('hidden');$('#add-welink-source').onclick=addWelinkSource;$('#wl-source-type').onchange=()=>{const user=$('#wl-source-type').value==='user';$('#wl-source-id').placeholder=user?'用户账号（如 a0012345）':'群组 ID';$('#wl-source-name').placeholder=user?'用户名称':'群组名称'};$$('[data-wl-range]').forEach(x=>x.onclick=()=>setWlRange(x.dataset.wlRange));$('#wl-start-time').onchange=e=>{const v=wlView();if(v){v.start=e.target.value;v.range='custom';invalidateWlView(v);renderWelink()}};$('#wl-end-time').onchange=e=>{const v=wlView();if(v){v.end=e.target.value;v.range='custom';invalidateWlView(v);renderWelink()}};$('#refresh-welink').onclick=refreshWelink;$('#wl-first-page').onclick=()=>{const v=wlView();if(v){v.page=1;renderWelinkMessages()}};$('#wl-prev-page').onclick=()=>{const v=wlView();if(v){v.page--;renderWelinkMessages()}};$('#wl-next-page').onclick=()=>{const v=wlView();if(v){v.page++;renderWelinkMessages()}};$('#wl-last-page').onclick=()=>{const v=wlView();if(v){v.page=Math.max(1,Math.ceil(v.items.length/state.pageSize));renderWelinkMessages()}};$('#open-welink-start').onclick=openWelinkStart;$('#welink-process-selected').onclick=processWelinkSelected;$('#welink-schedule-option').onclick=chooseWelinkSchedule;$('#start-welink-timer').onclick=startWelinkTimer;
  $('#update-later').onclick=()=>closeModal('update-modal');$('#update-download').onclick=async()=>{if(state.updateInfo.url)await call('open_external',state.updateInfo.url);if(state.updateInfo.force)await call('quit_app');else closeModal('update-modal')};
}

async function init(){bind();const r=await call('bootstrap');Object.assign(state,{settings:r.settings,serverPresets:r.serverPresets,configured:r.configured,rules:r.rules,blacklist:r.blacklist,welinkSources:r.welinkSources||[],emailTask:r.emailTask,emailSchedule:r.emailSchedule,welinkTask:r.welinkTask||{running:false},welinkSchedule:r.welinkSchedule||{active:false}});$('#version').textContent=`v${r.version}`;fillWelink();updateSchedule(r.emailSchedule);updateWelinkSchedule(r.welinkSchedule);renderEmails();$('#app').classList.remove('loading');setInterval(poll,1000);if(!r.configured)showSettings(true);else refreshEmails();checkVersion()}
window.addEventListener('pywebviewready',()=>init().catch(e=>toast(e.message,true)));
